language: ruby
cache: bundler
bundler_args: --jobs=3 --retry=3 --with cucumber test --without development production
rvm: 2.3.0
env: COVERAGE=true DISPLAY=:99.0
before_script:
  - firefox --version
  - foreman start --port 3000 1>/dev/null 2>&1 &
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
after_script:
  - pkill foreman
script:
  - bundle exec rubocop
  - bundle exec rails test
  - bundle exec cucumber
services:
  - redis-server
