language: ruby
cache: bundler
bundler_args: --jobs=3 --retry=3 --with cucumber test --without development production
rvm: 2.3.0
env:
  - COVERAGE=true
script:
  - bundle exec rubocop
  - bundle exec rails test
  - bundle exec cucumber
services:
  - redis-server
